---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 4.0.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.1.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.2.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.3.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.4.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.5.0" STRICT_VARIABLES=yes
matrix:
  exclude:
  # Ruby 2.2.0
  - rvm: 2.2.0
    env: PUPPET_VERSION="~> 3.7.0"
  - rvm: 2.2.0
    env: PUPPET_VERSION="~> 3.8.0"